import {SPACING, FONTS, BORDER_RADIUS} from '../../constants/theme';
import {TYPOGRAPHY} from '../../constants/design';

export interface Career {
  id: string;
  title: string;
  iconName: string;
  color: string;
  tagline: string;
  description: string;
  whatTheyDo: string[];
  funFact: string;
  becomeOne: string;
  superpowers: string[];
  coolTools: string[];
  salary: string;
  difficulty: 'Easy' | 'Medium' | 'Hard' | 'Super Hard';
  category: 'science' | 'creative' | 'tech' | 'business' | 'service' | 'sports';
  famousPakistanis?: string[];
}

export interface CareerCategory {
  id: string;
  label: string;
  emoji: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export const CAREER_CATEGORIES: CareerCategory[] = [
  {id: 'all', label: 'All', emoji: '🌟'},
  {id: 'science', label: 'Science', emoji: '🔬'},
  {id: 'tech', label: 'Tech', emoji: '💻'},
  {id: 'creative', label: 'Creative', emoji: '🎨'},
  {id: 'service', label: 'Service', emoji: '🤝'},
  {id: 'sports', label: 'Sports', emoji: '⚽'},
  {id: 'business', label: 'Business', emoji: '💼'},
];

export const KIDS_CAREERS: Career[] = [
  {
    id: 'doctor',
    title: 'Doctor',
    iconName: 'medkit',
    color: '#EF5350',
    tagline: 'Heal People & Save Lives!',
    description: 'Doctors are like real-life superheroes! They help sick people feel better and save lives every day.',
    whatTheyDo: ['Check if you are healthy', 'Give medicine to make you feel better', 'Do surgeries to fix problems inside body', 'Help babies come into the world'],
    funFact: 'The first Pakistani female doctor was Dr. Rashid Jahan, who inspired many girls to become doctors!',
    becomeOne: 'Study hard in science, pass MDCAT exam, complete 5 years of medical school + 1 year training',
    superpowers: ['Healing Touch', 'Problem Solving', 'Staying Calm', 'Never Giving Up'],
    coolTools: ['Stethoscope', 'X-Ray Machine', 'Medicine', 'Surgical Tools'],
    salary: 'PKR 100,000 - 800,000/month',
    difficulty: 'Super Hard',
    category: 'science',
    famousPakistanis: ['Dr. Nergis Mavalvala (Astrophysicist)', 'Dr. Ruth Pfau (Leprosy Fighter)'],
  },
  {
    id: 'engineer',
    title: 'Engineer',
    iconName: 'construct',
    color: '#42A5F5',
    tagline: 'Build Amazing Things!',
    description: 'Engineers are the builders of the world! They create buildings, bridges, computers, rockets, and everything cool.',
    whatTheyDo: ['Design buildings and bridges', 'Create apps and video games', 'Build robots and machines', 'Make cars and airplanes work'],
    funFact: 'The Pakistan Engineering Council has over 200,000 registered engineers. Some helped build the Karakoram Highway!',
    becomeOne: 'Be good at math, pass ECAT exam, complete 4 years of engineering university',
    superpowers: ['Problem Solving', 'Creativity', 'Math Wizardry', 'Building Stuff'],
    coolTools: ['Computer', 'Calculator', 'Drawing Tools', 'Measuring Tape'],
    salary: 'PKR 60,000 - 500,000/month',
    difficulty: 'Hard',
    category: 'tech',
    famousPakistanis: ['Dr. Atta-ur-Rahman (Scientist)', 'Munir Ahmad Khan (Nuclear Engineer)'],
  },
  {
    id: 'programmer',
    title: 'Programmer',
    iconName: 'code-slash',
    color: '#7E57C2',
    tagline: 'Create Apps & Games!',
    description: 'Programmers are like wizards who speak to computers! They create the apps, games, and websites you love.',
    whatTheyDo: ['Create video games like PUBG and Free Fire', 'Build apps for your phone', 'Make websites and social media', 'Teach robots and AI to think'],
    funFact: 'Arfa Karim from Pakistan was the youngest Microsoft Certified Professional at age 9! You can start coding today!',
    becomeOne: 'Learn coding languages, practice on computer, get degree in Computer Science',
    superpowers: ['Logic Master', 'Creative Thinking', 'Patience', 'Learning Fast'],
    coolTools: ['Computer', 'Coding Languages', 'Coffee', 'Internet'],
    salary: 'PKR 80,000 - 1,000,000/month (can earn in $$ too!)',
    difficulty: 'Medium',
    category: 'tech',
    famousPakistanis: ['Arfa Karim (Youngest MCP)', "Maria Umar (Founder, Women's Digital League)"],
  },
  {
    id: 'pilot',
    title: 'Pilot',
    iconName: 'airplane',
    color: '#26A69A',
    tagline: 'Fly High in the Sky!',
    description: 'Pilots are the captains of the sky! They fly huge airplanes and take people on amazing journeys around the world.',
    whatTheyDo: ['Fly airplanes across the world', 'Keep passengers safe in the sky', 'Navigate through clouds and weather', 'Talk to control towers'],
    funFact: 'PIA was one of the first airlines in Asia! Pakistani pilots fly to over 30 countries.',
    becomeOne: 'Good eyesight, join CAA cadet program or private flying school, pass medical tests',
    superpowers: ['Sharp Eyes', 'Quick Decisions', 'Staying Calm', 'Navigation Skills'],
    coolTools: ['Airplane', 'Flight Computer', 'Radio', 'Maps'],
    salary: 'PKR 300,000 - 1,500,000/month',
    difficulty: 'Hard',
    category: 'service',
    famousPakistanis: ['Ayesha Farooq (First Female Fighter Pilot)', 'Maryam Mujtaba (First Female PAF Pilot)'],
  },
  {
    id: 'teacher',
    title: 'Teacher',
    iconName: 'school',
    color: '#66BB6A',
    tagline: 'Shape Future Leaders!',
    description: 'Teachers are the builders of minds! They help children learn and grow into amazing adults.',
    whatTheyDo: ['Teach subjects like math, science, English', 'Help students understand difficult things', 'Organize fun activities and projects', 'Guide students to achieve dreams'],
    funFact: 'Dr. Abdul Qadeer Khan was taught by amazing teachers who inspired him to become a scientist!',
    becomeOne: 'Get good education, complete B.Ed degree, love to help others learn',
    superpowers: ['Patience', 'Explaining Clearly', 'Caring Heart', 'Inspiring Others'],
    coolTools: ['Books', 'Whiteboard', 'Computer', 'Creative Ideas'],
    salary: 'PKR 35,000 - 200,000/month',
    difficulty: 'Medium',
    category: 'service',
    famousPakistanis: ['Malala Yousafzai (Education Activist)', 'Sir Syed Ahmad Khan (Education Pioneer)'],
  },
  {
    id: 'artist',
    title: 'Artist / Designer',
    iconName: 'brush',
    color: '#EC407A',
    tagline: 'Create Beautiful Things!',
    description: 'Artists make the world beautiful! They create paintings, designs, animations, and everything pretty you see.',
    whatTheyDo: ['Draw and paint pictures', 'Design logos and posters', 'Create cartoon characters', 'Make beautiful decorations'],
    funFact: 'Pakistani truck art is famous worldwide! Artists earn in dollars by selling their art online.',
    becomeOne: 'Practice drawing daily, learn design software, join art school (optional)',
    superpowers: ['Creativity', 'Color Sense', 'Imagination', 'Patience'],
    coolTools: ['Pencils & Brushes', 'Computer/Tablet', 'Photoshop', 'Colors'],
    salary: 'PKR 50,000 - 400,000/month (can earn $$ freelancing!)',
    difficulty: 'Medium',
    category: 'creative',
    famousPakistanis: ['Sadequain (Painter)', 'Salima Hashmi (Artist)'],
  },
  {
    id: 'scientist',
    title: 'Scientist',
    iconName: 'flask',
    color: '#5C6BC0',
    tagline: 'Discover New Things!',
    description: 'Scientists are the explorers of knowledge! They discover cures for diseases, secrets of space, and how nature works.',
    whatTheyDo: ['Do experiments in labs', 'Discover new medicines', 'Study space and stars', 'Find solutions to world problems'],
    funFact: 'Dr. Abdus Salam from Pakistan won the Nobel Prize in Physics! He was the first Pakistani to win it.',
    becomeOne: 'Love asking questions, study science subjects, do research at university',
    superpowers: ['Curiosity', 'Careful Observation', 'Critical Thinking', 'Patience'],
    coolTools: ['Microscope', 'Lab Equipment', 'Computer', 'Research Papers'],
    salary: 'PKR 80,000 - 500,000/month',
    difficulty: 'Super Hard',
    category: 'science',
    famousPakistanis: ['Dr. Abdus Salam (Nobel Laureate)', 'Dr. Atta-ur-Rahman (Organic Chemist)'],
  },
  {
    id: 'chef',
    title: 'Chef',
    iconName: 'restaurant',
    color: '#FF7043',
    tagline: 'Cook Delicious Food!',
    description: 'Chefs are food artists! They create yummy dishes that make people happy and bring families together.',
    whatTheyDo: ['Create new recipes', 'Cook delicious meals', 'Run restaurant kitchens', 'Appear on cooking shows'],
    funFact: 'Pakistani biryani, nihari, and seekh kebabs are famous worldwide! Many Pakistani chefs work in top hotels.',
    becomeOne: 'Practice cooking at home, join culinary school, work in restaurants',
    superpowers: ['Taste Mastery', 'Creativity', 'Speed', 'Time Management'],
    coolTools: ['Knives', 'Pots & Pans', 'Spices', 'Oven'],
    salary: 'PKR 40,000 - 300,000/month',
    difficulty: 'Medium',
    category: 'creative',
    famousPakistanis: ['Zubaida Tariq (Cooking Expert)', 'Naheed Ansari (Celebrity Chef)'],
  },
  {
    id: 'athlete',
    title: 'Athlete / Sports Star',
    iconName: 'football',
    color: '#29B6F6',
    tagline: 'Win Medals & Championships!',
    description: 'Athletes are the champions! They represent their country in sports and inspire millions with their skills.',
    whatTheyDo: ['Play sports professionally', 'Represent Pakistan internationally', 'Train hard every day', 'Win medals and trophies'],
    funFact: 'Jahangir Khan won the World Squash Championship 10 times! Pakistan has produced many cricket legends.',
    becomeOne: 'Start playing a sport early, practice daily, join sports academies',
    superpowers: ['Physical Fitness', 'Determination', 'Team Spirit', 'Never Giving Up'],
    coolTools: ['Sports Equipment', 'Training Gear', 'Healthy Food', 'Coach'],
    salary: 'PKR 100,000 - Millions/month for top players',
    difficulty: 'Hard',
    category: 'sports',
    famousPakistanis: ['Jahangir Khan (Squash Legend)', 'Babar Azam (Cricket Captain)', 'Naseem Shah (Fast Bowler)'],
  },
  {
    id: 'youtuber',
    title: 'Content Creator',
    iconName: 'phone-portrait',
    color: '#FF5252',
    tagline: 'Entertain Millions Online!',
    description: 'Content creators are the new stars! They make videos, streams, and content that millions of people watch and love.',
    whatTheyDo: ['Create fun videos for YouTube', 'Stream games on Twitch', 'Share knowledge online', 'Build a community of fans'],
    funFact: 'Many Pakistani YouTubers have millions of subscribers! You can start with just a phone.',
    becomeOne: 'Choose your niche, create content regularly, learn video editing',
    superpowers: ['Creativity', 'Consistency', 'Communication', 'Understanding Trends'],
    coolTools: ['Phone/Camera', 'Microphone', 'Editing Software', 'Internet'],
    salary: 'PKR 0 - Millions/month (depends on views!)',
    difficulty: 'Easy',
    category: 'creative',
    famousPakistanis: ['Irfan Junejo (Vlogger)', 'Mooroo (Content Creator)', 'Ducky Bhai (Gaming)'],
  },
  {
    id: 'lawyer',
    title: 'Lawyer / Advocate',
    iconName: 'briefcase',
    color: '#8D6E63',
    tagline: 'Fight for Justice!',
    description: 'Lawyers are the defenders of justice! They help people solve problems and make sure everyone is treated fairly.',
    whatTheyDo: ['Help people in court cases', 'Write legal documents', 'Protect innocent people', 'Advise companies and families'],
    funFact: 'Quaid-e-Azam Muhammad Ali Jinnah was a brilliant lawyer before becoming the founder of Pakistan!',
    becomeOne: 'Study law (LLB degree), pass bar exam, practice in courts',
    superpowers: ['Public Speaking', 'Critical Thinking', 'Research Skills', 'Persuasion'],
    coolTools: ['Law Books', 'Legal Documents', 'Laptop', 'Black Coat'],
    salary: 'PKR 50,000 - 1,000,000/month',
    difficulty: 'Hard',
    category: 'service',
    famousPakistanis: ['Quaid-e-Azam M.A. Jinnah', 'Asma Jahangir (Human Rights)'],
  },
  {
    id: 'architect',
    title: 'Architect',
    iconName: 'home',
    color: '#78909C',
    tagline: 'Design Amazing Buildings!',
    description: 'Architects design the buildings we live in! They create beautiful houses, schools, malls, and skyscrapers.',
    whatTheyDo: ['Design homes and buildings', 'Create 3D models of structures', 'Make buildings safe and beautiful', 'Plan entire cities'],
    funFact: 'The Faisal Mosque in Islamabad was designed by Turkish architect and is shaped like a desert tent!',
    becomeOne: 'Love drawing and design, study architecture (5 years), get licensed',
    superpowers: ['Creativity', 'Spatial Thinking', 'Technical Drawing', 'Problem Solving'],
    coolTools: ['Drawing Board', 'CAD Software', '3D Printer', 'Models'],
    salary: 'PKR 60,000 - 400,000/month',
    difficulty: 'Hard',
    category: 'creative',
    famousPakistanis: ['Nayyar Ali Dada (Architect)', 'Habib Fida Ali (Urban Designer)'],
  },
  {
    id: 'nurse',
    title: 'Nurse',
    iconName: 'heart',
    color: '#F48FB1',
    tagline: 'Care for Patients with Love!',
    description: 'Nurses are the heart of hospitals! They take care of patients day and night with love and dedication.',
    whatTheyDo: ['Take care of sick patients', 'Give medicines and injections', 'Monitor patient health', 'Comfort patients and families'],
    funFact: 'During COVID-19, Pakistani nurses worked 24/7 as frontline heroes saving lives!',
    becomeOne: 'Complete nursing diploma or BSN degree, pass nursing council exam',
    superpowers: ['Caring Heart', 'Attention to Detail', 'Staying Calm', 'Physical Stamina'],
    coolTools: ['Stethoscope', 'Thermometer', 'Medicine Tray', 'Patient Charts'],
    salary: 'PKR 40,000 - 150,000/month',
    difficulty: 'Medium',
    category: 'science',
    famousPakistanis: ['Florence Nightingale inspired many Pakistani nurses!'],
  },
  {
    id: 'police',
    title: 'Police Officer',
    iconName: 'shield-checkmark',
    color: '#1E88E5',
    tagline: 'Protect & Serve!',
    description: 'Police officers are the guardians of safety! They protect people and catch bad guys to keep everyone safe.',
    whatTheyDo: ['Catch criminals and solve crimes', 'Help people in emergencies', 'Direct traffic safely', 'Protect important places'],
    funFact: 'Pakistan has the first all-women police station in Karachi to help female citizens!',
    becomeOne: 'Pass police exam, complete training at police academy, stay physically fit',
    superpowers: ['Bravery', 'Quick Thinking', 'Physical Strength', 'Helping Others'],
    coolTools: ['Uniform', 'Radio', 'Vehicle', 'First Aid Kit'],
    salary: 'PKR 40,000 - 200,000/month',
    difficulty: 'Hard',
    category: 'service',
    famousPakistanis: ['SSP Shehla Qureshi (Crime Fighter)', 'SP Tahir Dawar (Bravery Award)'],
  },
  {
    id: 'banker',
    title: 'Banker / Finance',
    iconName: 'cash',
    color: '#4CAF50',
    tagline: 'Master of Money!',
    description: 'Bankers are the money wizards! They help people save money, grow wealth, and make smart financial decisions.',
    whatTheyDo: ['Help people save and invest money', 'Give loans for businesses', 'Manage bank operations', 'Advise on financial planning'],
    funFact: 'Pakistan has digital banking apps now! JazzCash and Easypaisa changed how Pakistanis use money.',
    becomeOne: 'Study business/finance, get MBA or banking certification, work in banks',
    superpowers: ['Math Skills', 'Trustworthiness', 'Analysis', 'Communication'],
    coolTools: ['Computer', 'Calculator', 'Financial Software', 'Reports'],
    salary: 'PKR 60,000 - 500,000/month',
    difficulty: 'Medium',
    category: 'business',
    famousPakistanis: ['Mian Muhammad Mansha (Business Tycoon)', 'Shamshad Akhtar (Central Bank Governor)'],
  },
  {
    id: 'journalist',
    title: 'Journalist / Reporter',
    iconName: 'newspaper',
    color: '#607D8B',
    tagline: 'Tell the Truth to the World!',
    description: "Journalists are the truth seekers! They report news, uncover stories, and inform people about what's happening.",
    whatTheyDo: ['Report news on TV and newspapers', 'Interview important people', 'Investigate important stories', 'Write articles and make videos'],
    funFact: 'Pakistan has hundreds of TV channels and newspapers! Journalists keep people informed every day.',
    becomeOne: 'Study journalism or mass communication, work at news organizations, build your portfolio',
    superpowers: ['Curiosity', 'Writing Skills', 'Communication', 'Bravery'],
    coolTools: ['Camera', 'Microphone', 'Notebook', 'Computer'],
    salary: 'PKR 40,000 - 300,000/month',
    difficulty: 'Medium',
    category: 'creative',
    famousPakistanis: ['Hamid Mir (Senior Journalist)', 'Gharidah Farooqi (News Anchor)'],
  },
  {
    id: 'fashion',
    title: 'Fashion Designer',
    iconName: 'shirt',
    color: '#9C27B0',
    tagline: 'Create Stunning Styles!',
    description: 'Fashion designers create the clothes we wear! They design beautiful dresses, suits, and accessories.',
    whatTheyDo: ['Design clothes and accessories', 'Create fashion collections', 'Run fashion shows', 'Dress celebrities and brides'],
    funFact: 'Pakistani fashion designers are famous worldwide! HSY, Maria B, and Sana Safinaz dresses are loved globally.',
    becomeOne: 'Study fashion design, learn sketching and sewing, build your brand',
    superpowers: ['Creativity', 'Color Sense', 'Trend Awareness', 'Sewing Skills'],
    coolTools: ['Fabric', 'Sewing Machine', 'Sketch Pad', 'Mannequin'],
    salary: 'PKR 50,000 - 500,000/month',
    difficulty: 'Medium',
    category: 'creative',
    famousPakistanis: ['HSY (Fashion Icon)', 'Maria B (Designer)', 'Khaadi Founders'],
  },
  {
    id: 'musician',
    title: 'Musician / Singer',
    iconName: 'musical-notes',
    color: '#E91E63',
    tagline: 'Create Beautiful Music!',
    description: 'Musicians bring joy through music! They sing songs, play instruments, and create music that touches hearts.',
    whatTheyDo: ['Sing songs and perform concerts', 'Play musical instruments', 'Compose and write songs', 'Record music in studios'],
    funFact: 'Nusrat Fateh Ali Khan is known worldwide as the "King of Qawwali"! Pakistani music is loved globally.',
    becomeOne: 'Learn to sing or play instruments, practice daily, share your music',
    superpowers: ['Musical Talent', 'Creativity', 'Performance Skills', 'Discipline'],
    coolTools: ['Instruments', 'Microphone', 'Music Software', 'Recording Studio'],
    salary: 'PKR 20,000 - Millions/month (top artists)',
    difficulty: 'Medium',
    category: 'creative',
    famousPakistanis: ['Nusrat Fateh Ali Khan', 'Atif Aslam', 'Rahat Fateh Ali Khan', 'Ali Zafar'],
  },
  {
    id: 'vet',
    title: 'Veterinarian',
    iconName: 'paw',
    color: '#8BC34A',
    tagline: 'Heal Animals with Love!',
    description: 'Vets are animal doctors! They help pets, farm animals, and even zoo animals stay healthy and happy.',
    whatTheyDo: ['Treat sick animals', 'Give vaccinations to pets', 'Do surgeries on animals', 'Advise on animal care'],
    funFact: 'Pakistan has rescue organizations that save street animals! Vets help thousands of animals every year.',
    becomeOne: 'Study veterinary medicine (5 years), love animals, get licensed',
    superpowers: ['Animal Lover', 'Patience', 'Gentle Hands', 'Problem Solving'],
    coolTools: ['Stethoscope', 'Medicine', 'X-Ray', 'Surgical Tools'],
    salary: 'PKR 50,000 - 200,000/month',
    difficulty: 'Hard',
    category: 'science',
    famousPakistanis: ['Many animal rescue heroes in Pakistan!'],
  },
];

export const CAREER_QUIZ_QUESTIONS: Record<string, QuizQuestion[]> = {
  doctor: [
    {question: 'Do you genuinely enjoy helping sick people feel better, even when it is tough?', options: ['Yes! Helping is my purpose!', 'Sometimes, it depends', 'Not really my thing'], correctIndex: 0, explanation: 'Doctors who truly care about healing make the best physicians!'},
    {question: 'Which exam must Pakistani students pass to get into medical school?', options: ['MDCAT (Medical & Dental College Admission Test)', 'ECAT (Engineering College)', 'NET (NUST Entry Test)', 'GAT (Graduate Assessment Test)'], correctIndex: 0, explanation: 'MDCAT is the national entry test for MBBS/BDS admission in Pakistan!'},
    {question: 'A patient is very scared before surgery. How do you respond?', options: ['Calmly explain what will happen and reassure them', 'Tell them to stop worrying and be quiet', 'Leave it to the nurse to handle'], correctIndex: 0, explanation: 'Doctors need excellent communication and empathy skills!'},
    {question: 'How long does MBBS (Doctor) degree take in Pakistan?', options: ['5 years + 1 year house job = 6 years total', '3 years flat', '4 years like engineering', '2 years after FSc'], correctIndex: 0, explanation: 'MBBS is 5 years of medical school + 1 mandatory house job year!'},
    {question: 'You stay awake 30 hours on an emergency night shift. What keeps you going?', options: ['The patients who need me — that\'s why I became a doctor', 'Coffee, mostly coffee', 'I would quit and go home'], correctIndex: 0, explanation: 'The greatest doctors are driven by a deep commitment to their patients!'},
  ],
  engineer: [
    {question: 'Do you love figuring out HOW things work and then making them BETTER?', options: ['Yes! I take things apart to see inside!', 'Mildly curious', 'Not really'], correctIndex: 0, explanation: 'Engineers are driven by curiosity and the urge to improve!'},
    {question: 'Which entry test do most engineering universities in Pakistan require?', options: ['ECAT (Engineering College Admission Test)', 'MDCAT (Medical)', 'NET (NUST specific)', 'Both ECAT and NET depending on university'], correctIndex: 3, explanation: 'ECAT is for most universities, but NUST uses its own NET test. GIKI and PIEAS have separate tests too!'},
    {question: 'A bridge design has a small error. What do you do?', options: ['Carefully recheck all calculations and fix the error before building', 'Hope nobody notices', 'Build it anyway, it\'ll probably be fine'], correctIndex: 0, explanation: 'Attention to detail is critical — small errors in engineering can cost lives!'},
    {question: 'Which subject is MOST important for an engineering career?', options: ['Mathematics & Physics', 'Biology & Chemistry', 'English & History', 'Urdu & Islamic Studies'], correctIndex: 0, explanation: 'Math and Physics are the foundation of all engineering disciplines!'},
    {question: 'Pakistan needs cheaper solar energy solutions. You are tasked to design one. What excites you?', options: ['The challenge of making energy affordable for millions!', "It's fine, just another job", 'I would rather do a simpler project'], correctIndex: 0, explanation: 'Engineers who are passionate about solving real problems change the world!'},
  ],
  programmer: [
    {question: 'You spend 3 hours on a bug in your code, then finally fix it. You feel...', options: ['AMAZING — that feeling is why I code!', 'Relieved but frustrated', 'Never again am I coding'], correctIndex: 0, explanation: 'The best programmers love the debugging puzzle!'},
    {question: 'Which is the most popular programming language for beginners?', options: ['Python', 'Assembly', 'COBOL', 'Brainfuck'], correctIndex: 0, explanation: 'Python is beginner-friendly, powerful, and used in AI, web, and data science!'},
    {question: 'A user reports your app crashes when they tap the back button. What do you do?', options: ['Reproduce the bug, check error logs, and fix it systematically', 'Tell the user to not tap back then', 'Delete the app and start fresh'], correctIndex: 0, explanation: 'Debugging is a core skill — systematic thinking solves problems!'},
    {question: 'Which Pakistani achieved fame as the youngest Microsoft Certified Professional at age 9?', options: ['Arfa Karim', 'Malala Yousafzai', 'Dr. Nergis Mavalvala', 'Bilal Chaudhry'], correctIndex: 0, explanation: 'Arfa Karim from Faisalabad set a world record! She proved age is no barrier in tech!'},
    {question: 'Can Pakistani programmers earn in US Dollars from home?', options: ['Yes! Via freelancing on Upwork, Fiverr, and Toptal', 'No, you must be in the USA to earn dollars', 'Only if you have a Canadian visa'], correctIndex: 0, explanation: 'Pakistan is in the top 5 freelancing countries! Many devs earn $50-$150/hour remotely!'},
  ],
  pilot: [
    {question: 'You are flying through a storm. The plane shakes violently. You...', options: ['Stay calm, follow procedure, and guide the plane safely', 'Panic and let the co-pilot handle it', 'Turn the plane around immediately'], correctIndex: 0, explanation: 'Pilots train hundreds of hours specifically for emergencies to stay calm under pressure!'},
    {question: 'Which organization licenses pilots in Pakistan?', options: ['CAA (Civil Aviation Authority)', 'PIA HR Department', 'PEMRA (Pakistan Electronic Media)', 'NHA (National Highway Authority)'], correctIndex: 0, explanation: 'The Civil Aviation Authority (CAA) of Pakistan issues all pilot licenses!'},
    {question: 'How many hours of flying experience does a commercial pilot need before flying passengers?', options: ['At least 1,500 flight hours', 'Just 10 hours practice', '200 hours is enough', 'Experience doesn\'t matter, just pass the exam'], correctIndex: 0, explanation: 'Commercial pilots need 1,500+ logged flight hours before carrying passengers!'},
    {question: 'Which Pakistani aviator became famous as the first female fighter pilot?', options: ['Ayesha Farooq', 'Benazir Bhutto', 'Sharmeen Obaid', 'Maryam Nawaz'], correctIndex: 0, explanation: 'Squadron Leader Ayesha Farooq broke barriers as Pakistan\'s first female war-ready pilot!'},
    {question: 'Are you okay with irregular schedules, long flights, and time away from family?', options: ["Yes — the skies are worth it!", 'I would make it work', 'I prefer a fixed 9-5 schedule'], correctIndex: 0, explanation: 'Pilots have irregular schedules with night flights and international layovers — passion makes it worthwhile!'},
  ],
  teacher: [
    {question: 'Your student still doesn\'t understand after you explained it three times. You...', options: ['Try a completely different approach — maybe draw a picture or use an example', 'Ask them to study the book again', 'Give up, this student is not smart enough'], correctIndex: 0, explanation: 'Great teachers adapt their methods — every student learns differently!'},
    {question: 'Which degree do Pakistani teachers need for government school teaching?', options: ['B.Ed (Bachelor of Education)', 'MBBS (Doctor degree)', 'LLB (Law degree)', 'Any degree is enough with no training'], correctIndex: 0, explanation: 'B.Ed is the professional teaching qualification required in Pakistan!'},
    {question: 'What is the most powerful tool a teacher has?', options: ['Inspiring curiosity and love of learning', 'A big stick for discipline', 'Lots of homework assignments', 'Covering the syllabus as fast as possible'], correctIndex: 0, explanation: 'Teachers who inspire curiosity change lives forever. Sir Syed, Malala\'s father — they proved this!'},
    {question: 'Malala Yousafzai risked her life for what cause?', options: ["Girls' right to education in Pakistan", 'Pakistan\'s cricket team', 'Equal pay for teachers', 'Free university admissions'], correctIndex: 0, explanation: 'Malala\'s courage for education earned her the youngest-ever Nobel Peace Prize!'},
    {question: 'Do you enjoy seeing the moment when someone finally UNDERSTANDS something?', options: ['Yes! That moment is magical!', 'It\'s nice, not particularly special', 'Not really, I prefer working alone'], correctIndex: 0, explanation: 'The best teachers live for those breakthrough moments — it\'s the greatest reward!'},
  ],
  artist: [
    {question: 'You see a beautiful sunset. What is your first instinct?', options: ['I want to paint it, draw it, or photograph it!', 'Take a phone selfie for Instagram and move on', 'Nothing special — it\'s just a sunset'], correctIndex: 0, explanation: 'Artists see beauty everywhere and feel compelled to capture and share it!'},
    {question: 'Which Pakistani art form is recognized internationally as uniquely Pakistani?', options: ['Pakistani Truck Art (Jingle trucks)', 'Calligraphy only', 'Western oil painting', 'Manga comics'], correctIndex: 0, explanation: 'Pakistani truck art is a UNESCO-recognized cultural treasure loved worldwide!'},
    {question: 'Which software do most professional graphic designers use?', options: ['Adobe Photoshop & Illustrator', 'Microsoft Paint', 'Notepad', 'Google Docs'], correctIndex: 0, explanation: 'Adobe Creative Suite (Photoshop, Illustrator, InDesign) is the industry standard!'},
    {question: 'A client rejects your design and wants major changes. You...', options: ['Listen carefully, understand their vision, and redesign professionally', 'Argue that your design was perfect', 'Give up and refund them'], correctIndex: 0, explanation: 'Professional designers balance their artistic vision with client requirements!'},
    {question: 'Pakistani designers like HSY and Maria B export fashion globally. What does this mean for you?', options: ['I can build a Pakistani fashion/art brand that the world loves!', 'There\'s no room for new designers', 'Only Lahori designers can succeed'], correctIndex: 0, explanation: 'Pakistani art and fashion is globally sought-after — there has never been a better time to create!'},
  ],
  scientist: [
    {question: 'You do an experiment and the result is NOT what you expected. You...', options: ['Get excited — unexpected results lead to discoveries!', 'Declare the experiment a failure', 'Change the data to match what you expected'], correctIndex: 0, explanation: 'Penicillin, X-rays, and Teflon were ALL discovered by accident! Failed experiments fuel breakthroughs!'},
    {question: 'Which Pakistani scientist won the Nobel Prize in Physics?', options: ['Dr. Abdus Salam (1979)', 'Dr. Atta-ur-Rahman', 'Dr. Abdul Qadeer Khan', 'Dr. Nergis Mavalvala'], correctIndex: 0, explanation: 'Dr. Abdus Salam is Pakistan\'s only Nobel laureate — he won for his work on electroweak unification!'},
    {question: 'Pakistan has a serious clean water shortage. You are a scientist. You focus on...', options: ['Developing low-cost water purification technology', 'Studying rare butterflies in the Amazon', 'Whatever my professor tells me to study'], correctIndex: 0, explanation: 'The best scientists apply their skills to their nation\'s most urgent problems!'},
    {question: 'How long does getting a PhD (highest science degree) take after graduation?', options: ['4-6 years of research beyond a bachelor\'s degree', 'Just 1 extra year', '2 years like a master\'s', 'You don\'t need a PhD to be a scientist'], correctIndex: 0, explanation: 'A PhD takes 4-6 years of original research — but it opens doors to discovering new knowledge!'},
    {question: 'Friday science LAB day: Your preferred activity is...', options: ['Running experiments and analyzing results — time flies!', 'Taking notes from the board', 'Counting down to when lab ends'], correctIndex: 0, explanation: 'Labs are where scientists come alive! If lab time flies by for you, research is your calling!'},
  ],
  chef: [
    {question: 'You invent a new biryani recipe combining two regional styles. Friends try it and love it. You feel...', options: ['Creative ecstasy — I need to refine and perfect this!', 'Happy, but it was a lucky accident', 'Embarrassed — who am I to invent recipes?'], correctIndex: 0, explanation: 'Culinary innovation starts with fearlessly experimenting with flavors!'},
    {question: 'Restaurant kitchen at 7pm (rush hour): 50 orders, 3 chefs, all dishes needed in 10 minutes. You...', options: ['Organize the team, divide tasks, and deliver every dish hot and perfect', 'Panic under the pressure', 'Walk out until it calms down'], correctIndex: 0, explanation: 'Professional kitchens are controlled chaos — leadership and speed are essential!'},
    {question: 'Pakistani cuisine has which dish that is famous worldwide?', options: ['Biryani, Nihari, and Seekh Kebabs', 'Pizza and Sushi', 'French Croissant', 'Thai Green Curry'], correctIndex: 0, explanation: 'Pakistani biryani is ranked among the world\'s best dishes! Pakistani cuisine is globally celebrated!'},
    {question: 'Which school offers professional culinary training in Pakistan?', options: ['Culinary schools in Lahore/Karachi + hotel management institutes', 'Any cooking YouTube channel is enough', 'No formal training needed to be a chef', 'Only international culinary schools count'], correctIndex: 0, explanation: 'You can study at culinary institutes or start through hotel management programs in Pakistan!'},
    {question: 'A food critic gives your restaurant dish 2/5 stars in a review. Your reaction?', options: ['Study the criticism carefully and improve the dish', 'Ignore critics — they don\'t know good food', 'Remove the dish from the menu forever'], correctIndex: 0, explanation: 'Great chefs treat criticism as free cooking lessons — it\'s how they improve!'},
  ],
  athlete: [
    {question: 'Your team loses an important match. How do you react the next day at practice?', options: ['Train even harder — I will study what went wrong and improve', 'Skip practice, the defeat is too painful', 'Blame the referee and give up'], correctIndex: 0, explanation: 'Pakistan\'s greatest athletes — Imran Khan, Jahangir Khan — all built success on learning from defeats!'},
    {question: 'Which Pakistani squash player won the World Championship a world-record 10 times?', options: ['Jahangir Khan', 'Babar Azam', 'Shahid Afridi', 'Jansher Khan'], correctIndex: 0, explanation: 'Jahangir Khan is the greatest squash player in history — a true Pakistani legend!'},
    {question: 'Professional athletes typically train how many hours per day?', options: ['4-8 hours of structured training daily', '30 minutes when they feel like it', 'Only on match days', '1-2 hours casually'], correctIndex: 0, explanation: 'Elite athletes train 4-8 hours daily, sometimes twice a day — discipline is everything!'},
    {question: 'Eating junk food every day: what impact does it have on an athlete\'s performance?', options: ['Very negative — athletes need precise nutrition for peak performance', 'Very positive — more calories = more energy', 'No impact — genes matter not food', 'Only matters for bodybuilders'], correctIndex: 0, explanation: 'Sports nutrition is a science! What you eat directly affects speed, strength, and recovery!'},
    {question: 'If you miss making the national team at age 18, do you...', options: ['Keep developing at club level and try again at 21-22 — many late bloomers succeed!', 'Give up and choose another career', 'Go straight to international play via a different country'], correctIndex: 0, explanation: 'Many Pakistani athletes peaked late — consistency over years beats early talent!'},
  ],
  youtuber: [
    {question: 'You post a video that gets only 50 views after a week. You...', options: ['Study why it underperformed, improve, and post again consistently', 'Delete the channel — nobody cares', 'Buy fake views to boost the numbers'], correctIndex: 0, explanation: 'MrBeast posted for 5 years before going viral. Every successful creator had a slow start!'},
    {question: 'Pakistani YouTubers like Irfan Junejo earn from YouTube mainly through...', options: ['Ad revenue, brand deals, and merchandise sales', 'Only selling their phones to buy cameras', 'Purely from subscriptions (YouTube Red)', 'The Pakistan government pays YouTube creators'], correctIndex: 0, explanation: 'Content creators earn through AdSense, brand sponsorships, digital products, and community memberships!'},
    {question: 'What does "YouTube SEO" mean?', options: ['Using the right title, tags, and description so people can find your video', 'Search Engine Optimization for website ranking', 'A YouTube certification program', 'Only uploading videos in HD quality'], correctIndex: 0, explanation: 'SEO helps your videos appear in search results — it\'s critical for channel growth!'},
    {question: 'Your best performing video is about "Lahore Street Food." What should you do next?', options: ['Make more street food content — double down on what works!', 'Immediately switch to tech content since more creators do that', 'Delete it and never repeat the topic'], correctIndex: 0, explanation: 'Analyzing what works and doing more of it is the foundation of channel growth strategy!'},
    {question: 'Can Pakistani content creators earn money in US Dollars?', options: ['Yes! via YouTube AdSense, Patreon, and brand deals paid in USD', 'No, Pakistan is blocked from monetization', 'Only if you live in UAE or UK', 'Only for 1 million+ subscri channels'], correctIndex: 0, explanation: 'Pakistan\'s monetization rules have improved! Many creators earn thousands of dollars monthly!'},
  ],
  lawyer: [
    {question: 'Two people argue a legal case in front of you. Both have valid points. You...', options: ['Listen carefully to both sides before forming any judgment', 'Side with whoever speaks first and most confidently', 'Ask someone else to decide for you'], correctIndex: 0, explanation: 'Justice requires impartial, careful analysis of every argument — that\'s the foundation of law!'},
    {question: 'Quaid-e-Azam Muhammad Ali Jinnah was famous as a brilliant...', options: ['Barrister (Lawyer) before founding Pakistan', 'Medical doctor', 'Military general', 'Journalist and editor'], correctIndex: 0, explanation: 'Jinnah was one of the greatest lawyers in British India — he used legal argument to win independence!'},
    {question: 'Which degree do Pakistani students study to become a lawyer?', options: ['LLB (Bachelor of Laws) — 3-5 year program', 'MBA in legal studies', 'B.Com + license exam', 'Any bachelor\'s degree works'], correctIndex: 0, explanation: 'LLB from a recognized law school + enrollment in Pakistan Bar Council makes you a lawyer!'},
    {question: 'A client is innocent but the evidence looks bad. As their lawyer, you...', options: ['Build the strongest possible legal defense using all available facts', 'Tell them to plead guilty to make the case easier', 'Refuse the case because it looks difficult'], correctIndex: 0, explanation: 'Every accused deserves a proper defense — that\'s a cornerstone of justice!'},
    {question: 'Human rights lawyer Asma Jahangir was famous in Pakistan for...', options: ['Fearlessly defending minorities, women, and political prisoners', 'Representing large corporations in commercial disputes', 'Never taking controversial cases', 'Serving as Chief Justice of Pakistan'], correctIndex: 0, explanation: 'Asma Jahangir was a global icon of courage — she proved lawyers can change society!'},
  ],
  architect: [
    {question: 'You look at an empty plot of land. You see...', options: ['A building, park, or community space in my imagination!', 'Just empty land with no potential', 'A place to build whatever the client says, nothing more'], correctIndex: 0, explanation: 'Architects possess spatial visualization — the ability to see buildings that don\'t exist yet!'},
    {question: 'The iconic Faisal Mosque in Islamabad was designed to look like a...', options: ['Desert tent/Bedouin camp (Bedu tent shape)', 'Star and crescent moon', 'Traditional Mughal dome', 'Modern glass skyscraper'], correctIndex: 0, explanation: 'Designed by Turkish architect Vedat Dalokay, Faisal Mosque\'s tent shape is uniquely beautiful!'},
    {question: 'Architecture degree in Pakistan takes...', options: ['5 years (B.Arch) — the longest undergraduate design degree', '2 years like a diploma', '3 years same as computer science', '4 years like engineering'], correctIndex: 0, explanation: 'B.Arch is 5 years, followed by a 2-year probationary period before full licensure!'},
    {question: 'A client wants a larger building than the approved plan allows. You...', options: ['Explain the legal limits and find creative solutions within the law', 'Just build whatever the client wants — their money', 'Add extra floors secretly'], correctIndex: 0, explanation: 'Building codes protect lives — violating them risks collapse and criminal liability!'},
    {question: 'Climate change is making Pakistani summers hotter. As an architect, how do you respond?', options: ['Design buildings with natural ventilation, shade, and green roofs to reduce AC use', 'Just install bigger air conditioners', 'Ignore it — that\'s an environmental problem not a design problem'], correctIndex: 0, explanation: 'Sustainable architecture is now essential in Pakistan — green buildings save energy and lives!'},
  ],
  nurse: [
    {question: 'A patient is crying in pain at 3am and the doctor is busy in surgery. You...', options: ['Stay with them, provide comfort, give available pain relief, and inform the doctor', 'Tell them to wait quietly until morning', 'Go take a break — it\'s not your turn'], correctIndex: 0, explanation: 'Nurses are the constant caring presence patients rely on — they are the backbone of healthcare!'},
    {question: 'What does "BSN" stand for in nursing?', options: ['Bachelor of Science in Nursing', 'Basic Surgery & Nursing', 'British School of Nurses', 'Board of State Nurses'], correctIndex: 0, explanation: 'BSN is the 4-year degree that makes you a professional registered nurse in Pakistan!'},
    {question: 'During COVID-19, who were the true frontline heroes working 24/7 in Pakistan?', options: ['Nurses and healthcare workers', 'Government ministers', 'Delivery drivers', 'Soldiers'], correctIndex: 0, explanation: 'Pakistani nurses worked through COVID without proper PPE at first — their sacrifice was extraordinary!'},
    {question: 'A newly admitted patient is very scared about their diagnosis. You...', options: ['Sit with them, listen to their fears, and explain things clearly in simple language', 'Tell them the medical jargon and move to the next patient', 'Say "Don\'t worry!" and walk away quickly'], correctIndex: 0, explanation: 'Therapeutic communication — listening and reassuring — is a core nursing skill!'},
    {question: 'Can Pakistani nurses work abroad in countries like Saudi Arabia, UK, and Canada?', options: ['Yes! Pakistani nurses are highly recruited internationally', 'No, foreign countries only accept nurses from Western countries', 'Only if you have 20+ years experience'], correctIndex: 0, explanation: 'Pakistani nurses are in high international demand — many earn excellent salaries abroad!'},
  ],
  police: [
    {question: 'You see a group of young men harassing a woman on the street. Alone, you...', options: ['Intervene firmly and professionally to stop it, call for backup', 'Look away — it\'s none of your business', 'Take a video for social media'], correctIndex: 0, explanation: 'Police officers have a duty to protect the public, even when off-duty!'},
    {question: 'The highest police recruitment exam in Pakistan is called...', options: ['CSS (Central Superior Services) for ASP/DSP level', 'ECAT for engineering police', 'MDCAT for forensic medicine only', 'LUMS entry test'], correctIndex: 0, explanation: 'CSS exam leads to ASP (Assistant Superintendent of Police) — the elite officer cadre!'},
    {question: 'In Pakistan there is the first all-women police station in...', options: ['Karachi', 'Islamabad', 'Peshawar', 'Quetta'], correctIndex: 0, explanation: 'Karachi has Pakistan\'s first female police station, specifically designed to help female citizens!'},
    {question: 'A witness gives you contradicting information about a crime. You...', options: ['Record both accounts carefully, look for physical evidence to verify the truth', 'Believe whoever sounds more confident', 'Arrest both of them to be safe'], correctIndex: 0, explanation: 'Police investigations require gathering all evidence before drawing conclusions!'},
    {question: 'Being a police officer requires...', options: ['Physical fitness AND legal knowledge AND ethical judgment', 'Only physical strength matters', 'Just a uniform and authority', 'Political connections only in Pakistan'], correctIndex: 0, explanation: 'Modern policing requires strength, legal knowledge, communication skills, and unshakeable integrity!'},
  ],
  banker: [
    {question: 'You notice a slight error in a financial report that would affect thousands of accounts. You...', options: ['Report it immediately and have it corrected — accuracy is non-negotiable', 'Fix it quietly without telling anyone', 'Hope no one else notices'], correctIndex: 0, explanation: 'In banking, even a small error can have massive ripple effects. Integrity is everything!'},
    {question: 'Pakistan\'s digital revolution includes which popular mobile banking apps?', options: ['JazzCash and Easypaisa (changed how 220 million Pakistanis use money!)', 'Only foreign apps like PayPal', 'Banks don\'t have apps in Pakistan', 'OnCash is the only option'], correctIndex: 0, explanation: 'JazzCash and Easypaisa have financially included millions of unbanked Pakistanis — a revolution!'},
    {question: 'Which global banking qualification is most valued in Pakistan?', options: ['ACCA or CFA (Chartered Financial Analyst)', 'MBBS (Medical degree)', 'CSS exam only', 'ECAT for banking operations'], correctIndex: 0, explanation: 'ACCA, CFA, and MBA Finance are the golden qualifications for high-level banking careers in Pakistan!'},
    {question: 'Islamic Banking (Halal Banking) is important to Pakistani customers because...', options: ['It avoids interest (riba) which is prohibited in Islam', 'It offers higher interest rates than conventional banks', 'It is cheaper because no computers are used', 'Only government banks follow Islamic principles'], correctIndex: 0, explanation: 'Pakistan is a world leader in Islamic Banking — Meezan Bank is one of the largest Islamic banks globally!'},
    {question: 'A client wants a loan they clearly cannot afford to repay. You...', options: ['Honestly explain the risks and suggest a more suitable financial product', 'Approve it anyway — profit for the bank!', 'Deny without explanation'], correctIndex: 0, explanation: 'Ethical banking protects both clients and the bank from financial crises!'},
  ],
  journalist: [
    {question: 'You discover a major corruption scandal involving a powerful politician. You...', options: ['Carefully verify facts with multiple sources, then publish professionally', 'Publish immediately without verification for the scoop', 'Stay silent because it might be dangerous'], correctIndex: 0, explanation: 'Journalism\'s golden rule: verify, verify, verify before publishing — accuracy is sacred!'},
    {question: 'Freedom of press in Pakistan means journalists have the right to...', options: ['Report on public matters without government censorship (though challenges exist)', 'Print anything they want including lies', 'Only report what the government announces', 'Interview celebrities, not politicians'], correctIndex: 0, explanation: 'Press freedom is vital to democracy — brave Pakistani journalists have risked their lives for it!'},
    {question: 'Which famous Pakistani journalist is known for fearless investigative reporting?', options: ['Hamid Mir — survived an assassination attempt but kept reporting', 'A fictional journalist from a TV drama', 'A journalist who only covers sports', 'No Pakistani journalists are famous internationally'], correctIndex: 0, explanation: 'Hamid Mir, Arshad Sharif, and Gharidah Farooqi are globally recognized Pakistani journalists!'},
    {question: 'Digital journalism vs. print journalism: which is growing in Pakistan?', options: ['Digital — YouTube, Twitter, and online news sites have surpassed print readership', 'Print is growing faster — no one reads online', 'Both are exactly equal', 'Neither, Pakistanis don\'t read news'], correctIndex: 0, explanation: 'Pakistan now has 300+ million internet users — digital journalism is exploding!'},
    {question: 'A politician\'s spokesperson aggressively denies your story is true. You...', options: ['Ask for their official response on record, include it in the article, and publish with all verified evidence', 'Kill the story to avoid conflict', 'Change the story to match their version'], correctIndex: 0, explanation: 'Great journalists follow the facts, not pressure — and always give the right of reply!'},
  ],
  fashion: [
    {question: 'You are at a wedding and you notice an AMAZING combination of colors on a guest\'s outfit. You...', options: ['Immediately study it — memorize it and sketch it later!', 'Just think "nice colors" and forget about it', 'Take a photo just to mock it'], correctIndex: 0, explanation: 'Fashion designers are always observing, analyzing, and mentally filing away inspiration!'},
    {question: 'Pakistan\'s fashion designer HSY is famous internationally for...', options: ['Luxury bridal couture blending Pakistani tradition with modern design', 'Sports clothing for Pakistani cricketers', 'Budget ready-to-wear western clothes', 'Designing the Pakistan Army uniform'], correctIndex: 0, explanation: 'HSY (Hassan Sheheryar Yasin) dresses major celebrities and exports Pakistani fashion globally!'},
    {question: 'Fabric most associated with Pakistani traditional fashion is...', options: ['Lawn and Khaddar (used by millions for summer/winter shalwar kameez)', 'Denim jeans from the USA', 'Silk from China only', 'Plastic and nylon fibres'], correctIndex: 0, explanation: 'Pakistani lawn brands like Gul Ahmed and Al-Karam are billion-rupee industries!'},
    {question: 'A client orders a bridal dress but then wants 20 last-minute changes 2 days before the wedding. You...', options: ['Stay calm, assess what\'s feasible, communicate honestly, and do your best professionally', 'Refuse to make any changes', 'Give the client exactly what they request even if it ruins the design'], correctIndex: 0, explanation: 'Fashion designers must balance client satisfaction with professional expertise!'},
    {question: 'Can Pakistani fashion designers sell their work internationally online?', options: ['Yes! Via Instagram, Shopify, and international fashion weeks — Pakistan fashion is globally popular', 'No, only local physical stores are possible', 'International platforms block Pakistani designers', 'Only if headquartered in Dubai or London'], correctIndex: 0, explanation: 'Pakistani fashion exports are growing! Many designers have global clientele via Instagram and e-commerce!'},
  ],
  musician: [
    {question: 'You practise the same 16-bar section for 3 hours until it\'s perfect. This feels...', options: ['Like real progress — every perfect run makes me better', 'Incredibly boring and pointless', 'Like a punishment'], correctIndex: 0, explanation: 'Musicians who love perfecting their craft become the greats — deliberate practice is the secret!'},
    {question: 'Pakistani legend Nusrat Fateh Ali Khan was the King of...', options: ['Qawwali (Sufi devotional music)', 'Classical Hindustani ragas only', 'Pop music and film songs', 'Rock and metal music'], correctIndex: 0, explanation: 'NFAK\'s Qawwali transcended borders — he performed at world stages and collaborated with Peter Gabriel!'},
    {question: 'Which streaming platform pays royalties to Pakistani artists?', options: ['Spotify, YouTube Music, and Apple Music (accessible in Pakistan)', 'None — Pakistan is fully blocked', 'Only SoundCloud', 'Only TikTok'], correctIndex: 0, explanation: 'Spotify launched in Pakistan in 2022 — Pakistani artists now earn from global streams!'},
    {question: 'Atif Aslam became a massive Bollywood star. What was his path?', options: ['Started in Pakistan\'s music scene, then crossed over to Indian films naturally', 'Moved to India first then came back', 'Only made Pakistani music and refused Bollywood', 'His father was already a famous Bollywood actor'], correctIndex: 0, explanation: 'Atif started with "Doorie" in Pakistan — his talent was so powerful that India came calling!'},
    {question: 'Music studios in Pakistan are available in...', options: ['Karachi, Lahore, Islamabad — professional recording facilities are growing rapidly', 'Only in Bollywood Mumbai', 'Pakistan has no professional studios yet', 'Only one state-run studio in Islamabad'], correctIndex: 0, explanation: 'Pakistan\'s music industry is booming! Coke Studio, Nescafe Basement, and independent studios are thriving!'},
  ],
  entrepreneur: [
    {question: 'Your new business idea fails after 6 months. You...', options: ['Analyze exactly what went wrong, learn from it, and start smarter next time', 'Give up entrepreneurship forever', 'Blame everyone else for the failure'], correctIndex: 0, explanation: 'Every successful entrepreneur failed before they succeeded — Elon Musk, Jeff Bezos, and local titans all did!'},
    {question: 'Pakistani startup Careem (ride-hailing) became a unicorn ($1B company) then was acquired by...', options: ['Uber for over $3 billion — Pakistan\'s biggest-ever startup exit', 'Amazon for $500 million', 'It failed and closed down', 'It merged with PIA'], correctIndex: 0, explanation: 'Careem, founded by Mudassir Sheikha, was Pakistan\'s first tech unicorn — proof that Pakistani entrepreneurs can win globally!'},
    {question: 'To start a business in Pakistan, you MUST...', options: ['Register with SECP (Securities & Exchange Commission of Pakistan)', 'Get permission from your parents only', 'Have at least 10 million rupees to start', 'Be at least 30 years old by law'], correctIndex: 0, explanation: 'SECP registration is the first legal step. You can start a Pakistani company with just a few thousand rupees!'},
    {question: 'The BEST time to launch a tech startup in Pakistan is...', options: ['NOW — 300M internet users + young population + growing VC investment = perfect conditions', 'When you are 40 years old with experience', 'After getting an MBA from Harvard', 'Only when Pakistan economy fully stabilizes'], correctIndex: 0, explanation: 'Pakistan\'s startup scene is exploding NOW — Airlift, Bazaar, Jugnu, and Sary all launched in the last 5 years!'},
    {question: 'A successful entrepreneur\'s most important skill is...', options: ['Resilience + learning fast + attracting the right team', 'Having the most money to start with', 'Being the smartest person in the room', 'Never changing the original business plan'], correctIndex: 0, explanation: 'The world\'s top entrepreneurs all cite resilience as the #1 factor in their success!'},
  ],
};
