import type {GoalTemplate, UserGoal} from '../types/goals';

// Storage key for goals
export const GOALS_STORAGE_KEY = '@pakuni_user_goals';
export const STREAKS_STORAGE_KEY = '@pakuni_goal_streaks';

// Default empty goals - user needs to create their own
export const DEFAULT_GOALS: UserGoal[] = [];

// Goal templates - Comprehensive for Pakistani students
export const GOAL_TEMPLATES: GoalTemplate[] = [
  {
    id: 'university',
    title: 'Get into Dream University',
    iconName: 'school-outline',
    color: '#4573DF',
    category: 'education',
    difficulty: 'Hard',
    estimatedDays: 180,
    milestones: [
      'Research university requirements & deadlines',
      'Check eligibility criteria (marks, domicile)',
      'Achieve required FSc percentage (80%+)',
      'Register for entry test (NUST NET/FAST/GIKI)',
      'Complete 3 months entry test preparation',
      'Take mock tests weekly',
      'Apply before deadline',
      'Prepare for interview (if required)',
    ],
  },
  {
    id: 'marks',
    title: 'Improve My Marks',
    iconName: 'trending-up-outline',
    color: '#27ae60',
    category: 'academics',
    difficulty: 'Medium',
    estimatedDays: 90,
    milestones: [
      'Identify weak subjects',
      'Create daily study schedule',
      'Complete homework same day',
      'Take practice tests every weekend',
      'Review and correct mistakes',
      'Ask teachers for help on difficult topics',
      'Join study group for peer learning',
      'Achieve target marks in monthly test',
    ],
  },
  {
    id: 'scholarship',
    title: 'Get Scholarship',
    iconName: 'trophy-outline',
    color: '#f39c12',
    category: 'financial',
    difficulty: 'Hard',
    estimatedDays: 120,
    milestones: [
      'Research available scholarships (HEC, Need-based, Merit)',
      'Check eligibility for each scholarship',
      'Gather required documents (income certificate, etc.)',
      'Write compelling personal statement',
      'Get recommendation letters from teachers',
      'Submit application before deadline',
      'Prepare for scholarship interview',
      'Follow up on application status',
    ],
  },
  {
    id: 'career',
    title: 'Explore Career Options',
    iconName: 'briefcase-outline',
    color: '#9b59b6',
    category: 'career',
    difficulty: 'Easy',
    estimatedDays: 30,
    milestones: [
      'Take career aptitude quiz in app',
      'Research top 5 career paths',
      'Talk to professionals in each field',
      'Understand required qualifications',
      'Create career action plan',
    ],
  },
  {
    id: 'entry-test',
    title: 'Ace Entry Test',
    iconName: 'flask-outline',
    color: '#E74C3C',
    category: 'education',
    difficulty: 'Hard',
    estimatedDays: 90,
    milestones: [
      'Register for entry test',
      'Get past papers (5+ years)',
      'Complete Physics syllabus revision',
      'Complete Chemistry syllabus revision',
      'Complete Math/Biology syllabus revision',
      'Complete English/IQ section prep',
      'Solve 50+ past papers',
      'Take 10+ full mock tests',
      'Review weak areas',
      'Final revision before exam',
    ],
  },
  {
    id: 'english',
    title: 'Improve English Skills',
    iconName: 'language-outline',
    color: '#3498DB',
    category: 'skills',
    difficulty: 'Medium',
    estimatedDays: 60,
    milestones: [
      'Read English newspaper daily (15 mins)',
      'Learn 10 new words daily',
      'Watch English content with subtitles',
      'Practice speaking with someone',
      'Write one paragraph daily',
      'Take grammar quiz weekly',
      'Complete one English book',
    ],
  },
  {
    id: 'matric-fsc',
    title: 'Score 90%+ in Board Exams',
    iconName: 'ribbon-outline',
    color: '#1ABC9C',
    category: 'academics',
    difficulty: 'Hard',
    estimatedDays: 180,
    milestones: [
      'Complete syllabus 2 months early',
      'Solve past papers (10 years)',
      'Master important questions',
      'Create formula/key points sheets',
      'Daily 6+ hours focused study',
      'Weekly revision of all subjects',
      'Mock exam practice',
      'Final week intensive revision',
    ],
  },
  {
    id: 'time-management',
    title: 'Master Time Management',
    iconName: 'time-outline',
    color: '#E67E22',
    category: 'skills',
    difficulty: 'Easy',
    estimatedDays: 21,
    milestones: [
      'Track current time usage for 3 days',
      'Identify time-wasting activities',
      'Create weekly schedule template',
      'Use Pomodoro technique (25/5 mins)',
      'Limit social media to 30 mins/day',
      'Wake up at consistent time',
      'Maintain schedule for 2 weeks',
    ],
  },
];
